### ISSUE TITLE
LGBT Pride Shirts

### ISSUE THREAD

**Issue by xtoferprime** [bawdycaste/sales#1]
![](https://i.imgur.com/B9DlWJe.png)
![](https://i.imgur.com/VkM5dSO.png)

**Comment by jaison2000b** [comment]
Order sent, total came to $287.00
![Screenshot 2019-05-08 at 8 20 41 AM](https://user-images.githubusercontent.com/48086127/57543921-ab297980-730a-11e9-9e2d-b8d551da2cc0.png)

**Comment by xtoferprime** [comment]
@jaison2000b can we have a shirt pic here pls

**Comment by jaison2000b** [comment]
> @jaison2000b can we have a shirt pic here pls

![image_from_ios](https://user-images.githubusercontent.com/48086127/59154450-48212480-8a27-11e9-83ac-261888b2e4ce.jpg)
