### ISSUE TITLE
Bawdy Bag Restocking for Sac 04/20

### ISSUE THREAD

**Issue by xtoferprime** [bawdycaste/sales#2]
**Jaison Betsekas** [00:20]
Sales department is re-stocking for Mass Bawdy Bag creation next week, large orders of items to be placed on the cast card will be $92 in noise makers | $108 in party hats | $216 in :tp:

**Comment by xtoferprime** [comment]
@jaison2000b this should be part of the review of this item at the meeting

**Comment by jaison2000b** [comment]
Why?
